name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout'
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
        fetch-depth: 0
